From Fabien Tassin.  Under Linux innfeed compile fails with undefined reference to yydebug.  This changes declaration from extern int yydebug; to int yydebug;.
If this breaks other compilations, let us know.  I didn't test
it. -- Forrest Cavalier